GET http://localhost:3000/api/health

###GET

### Buscar Usuario por ID
GET http://localhost:3000/api/users/1

### Atualizar Usuario
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{ 
    "nome": "Arthur Parra",
    "email": "arthur.parra@gmail.com"
}

### excluir Usuario
DELETE http://localhost:3000/api/users/1
